ALTER TABLE tb_usuarios
ADD cep VARCHAR(255),
ADD logradouro VARCHAR(255),
ADD complemento VARCHAR(255),
ADD bairro VARCHAR(255),
ADD localidade VARCHAR(255),
ADD uf VARCHAR(255),
ADD ddd BIGINT,
ADD numero VARCHAR(255);